<?php

namespace Dizzy\RssReaderBundle\Document\Repositories;

use Dizzy\RssReaderBundle\Document\Feed;
use Dizzy\RssReaderBundle\Document\User;
use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Feed
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends DocumentRepository
{
    public function getUserFeeds(User $user)
    {
        $qb = $this->createQueryBuilder();

        $qb->field('users')->includesReferenceTo($user);
        $qb->map('function() {emit(this._id, (this.posts ? this.posts.length : 0))}');
        $qb->reduce('function(k, vals) { return vals; }');

        return $qb->getQuery()->execute();
    }

    public function countUnreadPosts(User $user, Feed $feed)
    {
        $qb = $this->createQueryBuilder();
        $qb->select(['posts']);
        $qb->field('users')->includesReferenceTo($user);
//        $qb->group('posts',)

        return $qb->getQuery()->getSingleResult();
    }
}