<?php

namespace Dizzy\RssReaderBundle\Document\Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * User
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends DocumentRepository
{
}