services:
    rss.angular_post_listener:
        class: Dizzy\RssReaderBundle\EventListener\AngularPostListener
        arguments: [ @service_container ]
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    rss.tokens.action_listener:
        class: Dizzy\RssReaderBundle\EventListener\TokenListener
        arguments: [ @service_container ]
        tags:
          - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
    rss.fetch:
        class: Dizzy\RssReaderBundle\Services\SimplePie
        arguments: ["@service_container"]
    rss.import.opml:
        class: Dizzy\RssReaderBundle\Services\ImportOPML
        arguments: ["@service_container"]

